# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - appstudentexamperformance

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://testdockervipul.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_f942ab7ea32a4322aa20f922cd29c196 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e384dabd0c0946d1a388ced0fa028f84 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: testdockervipul.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f942ab7ea32a4322aa20f922cd29c196 }}/studentexamapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'appstudentexamperformance'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_43d05cf7f26e41ab891caddd000c5e4a }}
        images: 'testdockervipul.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f942ab7ea32a4322aa20f922cd29c196 }}/studentexamapp:${{ github.sha }}'